// All learning content extracted from Victor's Spanish 8 documents.
// Each area has words and/or sentences with Spanish + Swedish.

const DATA = {
  areas: [
    {
      id: "presentacion",
      name: "Presentationsfraser",
      icon: "👋",
      isNew: true,
      description: "Presentera dig själv på spanska",
      sentences: [
        { es: "¿Cómo te llamas?", sv: "Vad heter du?" },
        { es: "Me llamo...", sv: "Jag heter..." },
        { es: "¿Cuántos años tienes?", sv: "Hur gammal är du?" },
        { es: "Tengo... años.", sv: "Jag är ... år." },
        { es: "¿De dónde eres?", sv: "Varifrån kommer du?" },
        { es: "Soy de...", sv: "Jag kommer från ..." },
        { es: "¿Dónde vives?", sv: "Var bor du?" },
        { es: "Vivo en...", sv: "Jag bor i ..." },
        { es: "¿Hablas español?", sv: "Pratar du spanska?" },
        { es: "Sí, hablo español, inglés y sueco.", sv: "Ja, jag pratar spanska, engelska och svenska." },
        { es: "¿Estudias español en la escuela?", sv: "Pluggar du spanska i skolan?" },
        { es: "Sí, estudio español en la escuela.", sv: "Ja, jag pluggar spanska i skolan." },
        { es: "¿Te gusta el fútbol?", sv: "Tycker du om fotboll?" },
        { es: "Sí, me gusta mucho.", sv: "Ja, jag tycker mycket om det." },
        { es: "No, no me gusta.", sv: "Nej, det tycker jag inte om." },
        { es: "Pero me gusta el bandy de sala.", sv: "Men jag tycker om innebandy." },
        { es: "¿Tienes hermanos?", sv: "Har du syskon?" },
        { es: "Sí, tengo dos hermanas y un hermano.", sv: "Ja, jag har två systrar och en bror." },
        { es: "No, no tengo hermanos.", sv: "Nej, jag har inte syskon." },
        { es: "¿Tienes animales?", sv: "Har du husdjur?" },
        { es: "Sí, tengo un gato y dos perros.", sv: "Ja, jag har en katt och två hundar." },
        { es: "No, no tengo animales.", sv: "Nej, jag har inga husdjur." },
        { es: "Soy alérgico/alérgica.", sv: "Jag är allergisk." },
        { es: "¿Estás aquí toda la semana?", sv: "Är du här hela veckan?" },
        { es: "Sí, estoy aquí toda la semana.", sv: "Ja, jag är här hela veckan." }
      ]
    },
    {
      id: "veckodagar",
      name: "Veckodagar",
      icon: "📆",
      isNew: true,
      description: "Dagar i veckan och tidsuttryck",
      words: [
        { es: "semana (la)", sv: "vecka" },
        { es: "lunes", sv: "måndag" },
        { es: "martes", sv: "tisdag" },
        { es: "miércoles", sv: "onsdag" },
        { es: "jueves", sv: "torsdag" },
        { es: "viernes", sv: "fredag" },
        { es: "sábado", sv: "lördag" },
        { es: "domingo", sv: "söndag" }
      ],
      sentences: [
        { es: "¿Qué día es hoy?", sv: "Vilken dag är det idag?" },
        { es: "el lunes que viene", sv: "nästa måndag" },
        { es: "la semana que viene", sv: "nästa vecka" },
        { es: "el lunes pasado", sv: "förra måndag" },
        { es: "la semana pasada", sv: "förra veckan" }
      ]
    },
    {
      id: "datum",
      name: "Datum, månader och årstider",
      icon: "🗓️",
      isNew: true,
      description: "Månader, datum och årstider på spanska",
      words: [
        { es: "mes (el)", sv: "månad" },
        { es: "enero", sv: "januari" },
        { es: "febrero", sv: "februari" },
        { es: "marzo", sv: "mars" },
        { es: "abril", sv: "april" },
        { es: "mayo", sv: "maj" },
        { es: "junio", sv: "juni" },
        { es: "julio", sv: "juli" },
        { es: "agosto", sv: "augusti" },
        { es: "septiembre", sv: "september" },
        { es: "octubre", sv: "oktober" },
        { es: "noviembre", sv: "november" },
        { es: "diciembre", sv: "december" },
        { es: "estación (la)", sv: "årstid" },
        { es: "verano (el)", sv: "sommar" },
        { es: "otoño (el)", sv: "höst" },
        { es: "invierno (el)", sv: "vinter" },
        { es: "primavera (la)", sv: "vår" }
      ],
      sentences: [
        { es: "¿Qué fecha es hoy?", sv: "Vilket datum är det idag?" },
        { es: "Es el 10 de abril.", sv: "Det är den 10 april." },
        { es: "¿Cuándo es tu cumpleaños?", sv: "När är din födelsedag?" }
      ]
    },
    {
      id: "klader",
      name: "Kläder",
      icon: "👕",
      isNew: true,
      description: "Kläder och accessoarer på spanska",
      words: [
        { es: "ropa (la)", sv: "kläder" },
        { es: "probador (el)", sv: "provhytt" },
        { es: "caja (la)", sv: "kassa" },
        { es: "jersey (el)", sv: "tröja" },
        { es: "camiseta (la)", sv: "T-shirt" },
        { es: "vestido (el)", sv: "klänning" },
        { es: "falda (la)", sv: "kjol" },
        { es: "camisa (la)", sv: "skjorta" },
        { es: "pantalones (los)", sv: "byxor" },
        { es: "vaqueros (los)", sv: "jeans" },
        { es: "gorra (la)", sv: "keps" },
        { es: "gorro (el)", sv: "mössa" },
        { es: "chaqueta (la)", sv: "jacka" },
        { es: "biquini (el)", sv: "bikini" },
        { es: "shorts", sv: "shorts" },
        { es: "botas (las)", sv: "stövlar" },
        { es: "zapatos (los)", sv: "skor" },
        { es: "zapatillas (las)", sv: "gymnastikskor" },
        { es: "bufanda (la)", sv: "halsduk" },
        { es: "cinturón (el)", sv: "skärp" },
        { es: "calcetines (los)", sv: "strumpor" },
        { es: "guantes (los)", sv: "vantar" },
        { es: "sandalias (las)", sv: "sandaler" },
        { es: "ropa interior (la)", sv: "underkläder" }
      ]
    },
    {
      id: "farger",
      name: "Färger",
      icon: "🎨",
      isNew: true,
      description: "Färger på spanska",
      words: [
        { es: "color (el)", sv: "färg" },
        { es: "azul", sv: "blå" },
        { es: "verde", sv: "grön" },
        { es: "rojo", sv: "röd" },
        { es: "amarillo", sv: "gul" },
        { es: "blanco", sv: "vit" },
        { es: "negro", sv: "svart" },
        { es: "gris", sv: "grå" },
        { es: "marrón", sv: "brun" },
        { es: "naranja", sv: "orange" },
        { es: "lila", sv: "lila" },
        { es: "rosa", sv: "rosa" }
      ]
    },
    {
      id: "klockan",
      name: "Klockan",
      icon: "🕐",
      isNew: true,
      description: "Klockan och tid på spanska",
      words: [
        { es: "y", sv: "över (klockan)" },
        { es: "menos", sv: "i (klockan)" },
        { es: "media", sv: "halv" },
        { es: "cuarto", sv: "kvart" },
        { es: "¿A qué hora?", sv: "Vilken tid?" }
      ],
      sentences: [
        { es: "Es la una.", sv: "Klockan är ett." },
        { es: "Es la una y media.", sv: "Klockan är halv två." },
        { es: "Son las doce.", sv: "Klockan är tolv." },
        { es: "Son las doce y cinco.", sv: "Klockan är fem över tolv." },
        { es: "Son las dos y cuarto.", sv: "Klockan är kvart över två." },
        { es: "Son las dos y media.", sv: "Klockan är halv tre." },
        { es: "Son las cinco menos veinte.", sv: "Klockan är tjugo i fem." },
        { es: "Son las cuatro menos cuarto.", sv: "Klockan är kvart i fyra." },
        { es: "Son las diez menos diez.", sv: "Klockan är tio i tio." },
        { es: "¿A qué hora sale el tren?", sv: "Vilken tid avgår tåget?" },
        { es: "El tren sale a la una menos cuarto.", sv: "Tåget avgår klockan kvart i ett." },
        { es: "El tren sale a las tres y veinte.", sv: "Tåget avgår klockan tjugo över tre." }
      ]
    },
    {
      id: "familj",
      name: "Familjeord och andra personer",
      icon: "👨‍👩‍👧",
      isNew: true,
      description: "Familjemedlemmar och personbeteckningar",
      words: [
        { es: "familia (la)", sv: "familj" },
        { es: "padre (el)", sv: "pappa" },
        { es: "madre (la)", sv: "mamma" },
        { es: "padres (los)", sv: "föräldrar" },
        { es: "hermano (el)", sv: "bror" },
        { es: "hermana (la)", sv: "syster" },
        { es: "hermanos (los)", sv: "syskon" },
        { es: "abuelo (el)", sv: "morfar/farfar" },
        { es: "abuela (la)", sv: "mormor/farmor" },
        { es: "abuelos (los)", sv: "far- och morföräldrar" },
        { es: "tío (el)", sv: "morbror/farbror" },
        { es: "tía (la)", sv: "faster/moster" },
        { es: "primo (el)", sv: "kusin (kille)" },
        { es: "prima (la)", sv: "kusin (tjej)" },
        { es: "pareja (la)", sv: "partner" },
        { es: "marido (el)", sv: "make" },
        { es: "esposa (la)", sv: "fru (maka)" },
        { es: "novio (el)", sv: "pojkvän" },
        { es: "novia (la)", sv: "flickvän" },
        { es: "hombre (el)", sv: "man" },
        { es: "mujer (la)", sv: "kvinna" },
        { es: "chico (el)", sv: "pojke" },
        { es: "chica (la)", sv: "flicka" },
        { es: "amigo (el)", sv: "vän (kille)" },
        { es: "amiga (la)", sv: "vän (tjej)" },
        { es: "señor (el)", sv: "herr" },
        { es: "señora (la)", sv: "fru (titel)" },
        { es: "señorita (la)", sv: "fröken" }
      ]
    },
    {
      id: "utseende",
      name: "Utseende",
      icon: "👀",
      isNew: true,
      description: "Beskriv utseende — hår, ögon och kropp",
      words: [
        { es: "alto/alta", sv: "lång" },
        { es: "bajo/baja", sv: "kort" },
        { es: "delgado/delgada", sv: "smal" },
        { es: "gordito/gordita", sv: "knubbig" },
        { es: "musculoso/musculosa", sv: "muskulös" },
        { es: "pellirrojo/pellirroja", sv: "rödhårig" },
        { es: "moreno/morena", sv: "mörkhårig" },
        { es: "rubio/rubia", sv: "blond" },
        { es: "pelo moreno (el)", sv: "mörkt hår" },
        { es: "pelo rubio (el)", sv: "blont hår" },
        { es: "pelo liso (el)", sv: "rakt hår" },
        { es: "pelo rizado (el)", sv: "lockigt hår" },
        { es: "pelo corto (el)", sv: "kort hår" },
        { es: "pelo largo (el)", sv: "långt hår" },
        { es: "flequillo (el)", sv: "lugg" },
        { es: "pecas (las)", sv: "fräknar" },
        { es: "hoyuelos (los)", sv: "smilgropar" },
        { es: "ojos verdes (los)", sv: "gröna ögon" },
        { es: "ojos azules (los)", sv: "blå ögon" },
        { es: "ojos marrones (los)", sv: "bruna ögon" }
      ],
      sentences: [
        { es: "Soy moreno.", sv: "Jag är mörkhårig." },
        { es: "Tengo pelo moreno.", sv: "Jag har mörkt hår." },
        { es: "Soy bastante alto.", sv: "Jag är ganska lång." },
        { es: "Tengo los ojos azules.", sv: "Jag har blå ögon." }
      ]
    },
    {
      id: "staden",
      name: "I staden",
      icon: "🏙️",
      isNew: true,
      description: "Platser och byggnader i staden",
      words: [
        { es: "cine (el)", sv: "bio" },
        { es: "banco (el)", sv: "bank" },
        { es: "hospital (el)", sv: "sjukhus" },
        { es: "restaurante (el)", sv: "restaurang" },
        { es: "tienda (la)", sv: "affär" },
        { es: "farmacia (la)", sv: "apotek" },
        { es: "hotel (el)", sv: "hotell" },
        { es: "hostal (el)", sv: "vandrarhem" },
        { es: "comisaría (la)", sv: "polisstation" },
        { es: "metro (el)", sv: "tunnelbana" },
        { es: "parada de autobús (la)", sv: "busshållsplats" },
        { es: "cafetería (la)", sv: "kafé" },
        { es: "escuela (la)", sv: "skola" },
        { es: "iglesia (la)", sv: "kyrka" },
        { es: "librería (la)", sv: "bokhandel/bibliotek" },
        { es: "playa (la)", sv: "strand" },
        { es: "parque (el)", sv: "park" },
        { es: "calle (la)", sv: "gata" },
        { es: "supermercado (el)", sv: "stormarknad" }
      ]
    },
    {
      id: "prepositioner",
      name: "Prepositioner och lägesord",
      icon: "📍",
      isNew: true,
      description: "Var och hur saker befinner sig",
      words: [
        { es: "aquí", sv: "här" },
        { es: "allá", sv: "där" },
        { es: "afuera", sv: "utanför" },
        { es: "dentro", sv: "inuti" },
        { es: "a la derecha", sv: "till höger" },
        { es: "a la izquierda", sv: "till vänster" },
        { es: "al lado", sv: "bredvid" },
        { es: "en el centro", sv: "i mitten" },
        { es: "encima", sv: "ovanför" },
        { es: "debajo", sv: "under" },
        { es: "alrededor", sv: "runt om" },
        { es: "lejos", sv: "långt bort" },
        { es: "cerca", sv: "nära" },
        { es: "enfrente", sv: "mittemot" }
      ],
      sentences: [
        { es: "Vive cerca del estadio.", sv: "Han bor nära stadion." },
        { es: "Vamos al restaurante.", sv: "Vi går till restaurangen." },
        { es: "Está a la derecha de mi casa.", sv: "Den är till höger om mitt hus." },
        { es: "¿Dónde está la escuela?", sv: "Var ligger skolan?" }
      ]
    },
    {
      id: "fragor",
      name: "Frågeord",
      icon: "❓",
      description: "Frågeord på spanska — vad, var, när, varför...",
      words: [
        { es: "¿Cómo?", sv: "hur" },
        { es: "¿De dónde?", sv: "varifrån" },
        { es: "¿Quién?", sv: "vem" },
        { es: "¿Cuándo?", sv: "när" },
        { es: "¿Cuántos?", sv: "hur många" },
        { es: "¿Por qué?", sv: "varför" },
        { es: "¿Dónde?", sv: "var" },
        { es: "¿Cuál?", sv: "vilken" },
        { es: "¿Adónde?", sv: "vart" },
        { es: "¿Qué?", sv: "vad" },
        { es: "¿Cuánto?", sv: "hur mycket" }
      ],
      sentences: [
        { es: "¿Cuántos hermanos tienes?", sv: "Hur många syskon har du?" },
        { es: "¿Qué comes?", sv: "Vad äter du?" },
        { es: "¿Cuándo terminas hoy?", sv: "När slutar du idag?" },
        { es: "¿Dónde vives?", sv: "Var bor du?" },
        { es: "¿Quién es la chica allí?", sv: "Vem är tjejen där?" },
        { es: "¿Por qué no estás bien?", sv: "Varför mår du inte bra?" },
        { es: "¿Cuánto cuesta la falda?", sv: "Hur mycket kostar kjolen?" },
        { es: "¿Dónde está mi lápiz?", sv: "Var är min penna?" }
      ]
    },
    {
      id: "smaord",
      name: "Småord",
      icon: "🔗",
      description: "Vanliga småord och bindeord",
      words: [
        { es: "también", sv: "också" },
        { es: "solo", sv: "bara" },
        { es: "ahora", sv: "nu" },
        { es: "pero", sv: "men" },
        { es: "cuando", sv: "när" },
        { es: "con", sv: "med" },
        { es: "después", sv: "sen" },
        { es: "un poco", sv: "lite" },
        { es: "siempre", sv: "alltid" },
        { es: "nunca", sv: "aldrig" },
        { es: "a veces", sv: "ibland" },
        { es: "a menudo", sv: "ofta" },
        { es: "además", sv: "dessutom" }
      ]
    },
    {
      id: "kropp",
      name: "Kroppen",
      icon: "🧍",
      description: "Kroppsdelar",
      words: [
        { es: "la cabeza", sv: "huvudet" },
        { es: "el pelo", sv: "håret" },
        { es: "el brazo", sv: "armen" },
        { es: "el corazón", sv: "hjärtat" },
        { es: "la pierna", sv: "benet" },
        { es: "la mano", sv: "handen" },
        { es: "la nariz", sv: "näsan" },
        { es: "los dedos", sv: "fingrarna" },
        { es: "la cara", sv: "ansiktet" },
        { es: "la garganta", sv: "halsen" },
        { es: "los ojos", sv: "ögonen" },
        { es: "la boca", sv: "munnen" },
        { es: "la rodilla", sv: "knät" },
        { es: "el estómago", sv: "magen" },
        { es: "el pie", sv: "foten" },
        { es: "la espalda", sv: "ryggen" },
        { es: "las orejas", sv: "öronen" }
      ],
      sentences: [
        { es: "Le duele el estómago.", sv: "Han har ont i magen." },
        { es: "¿Le duelen las manos?", sv: "Har hon ont i händerna?" },
        { es: "Me duele un poco la espalda.", sv: "Jag har lite ont i ryggen." },
        { es: "Le duele mucho la garganta.", sv: "Han har mycket ont i halsen." },
        { es: "¿Te duele la cabeza ahora?", sv: "Har du ont i huvudet nu?" },
        { es: "Me duelen las orejas pero no me duelen los ojos.", sv: "Jag har ont i öronen men jag har inte ont i ögonen." },
        { es: "Me duele la pierna cuando me muevo con muletas.", sv: "Jag har ont i benet när jag rör mig med kryckor." },
        { es: "¿Te duele también?", sv: "Har du också ont?" }
      ]
    },
    {
      id: "hus",
      name: "Hus och möbler",
      icon: "🏠",
      description: "Rum, möbler och saker hemma",
      words: [
        { es: "la puerta", sv: "dörren" },
        { es: "la cama", sv: "sängen" },
        { es: "la mesa", sv: "bordet" },
        { es: "el escritorio", sv: "skrivbordet" },
        { es: "la sala de estar", sv: "vardagsrummet" },
        { es: "la alfombra", sv: "mattan" },
        { es: "la habitación", sv: "rummet" },
        { es: "el dormitorio", sv: "sovrummet" },
        { es: "la almohada", sv: "kudden" },
        { es: "la silla", sv: "stolen" },
        { es: "el armario", sv: "garderoben" },
        { es: "el espejo", sv: "spegeln" },
        { es: "la ventana", sv: "fönstret" },
        { es: "la cómoda", sv: "byrån" },
        { es: "el cuarto de baño", sv: "badrummet" },
        { es: "el sofá", sv: "soffan" },
        { es: "la lámpara", sv: "lampan" },
        { es: "las cortinas", sv: "gardinerna" },
        { es: "el pasillo", sv: "hallen" },
        { es: "la mesita de noche", sv: "nattduksbordet" },
        { es: "el sillón", sv: "fåtöljen" },
        { es: "la cocina", sv: "köket" },
        { es: "el cuadro", sv: "tavlan" },
        { es: "la estantería", sv: "bokhyllan" }
      ]
    },
    {
      id: "vader",
      name: "Vädret",
      icon: "☀️",
      description: "Hur vädret är",
      words: [
        { es: "hace sol", sv: "det är soligt" },
        { es: "hace calor", sv: "det är varmt" },
        { es: "hace frío", sv: "det är kallt" },
        { es: "hace buen tiempo", sv: "det är fint väder" },
        { es: "hace mal tiempo", sv: "det är dåligt väder" },
        { es: "está claro", sv: "det är klart" },
        { es: "hace viento", sv: "det är blåsigt" },
        { es: "llueve", sv: "det regnar" },
        { es: "nieva", sv: "det snöar" },
        { es: "está nublado", sv: "det är molnigt" },
        { es: "hace veinte grados", sv: "det är tjugo grader" },
        { es: "hace dos grados bajo cero", sv: "det är två minusgrader" },
        { es: "hay tormenta", sv: "det stormar" },
        { es: "está tronando", sv: "det åskar" },
        { es: "hay niebla", sv: "det är dimmigt" },
        { es: "¿Qué tiempo hace?", sv: "Vad är det för väder?" }
      ]
    },
    {
      id: "matlagning",
      name: "Matlagningsverb",
      icon: "🍳",
      description: "Verb för att laga mat",
      words: [
        { es: "cocinar", sv: "laga mat" },
        { es: "añadir", sv: "lägga till" },
        { es: "preparar", sv: "förbereda" },
        { es: "poner", sv: "ställa" },
        { es: "cortar", sv: "skära" },
        { es: "calentar", sv: "värma" },
        { es: "picar", sv: "hacka" },
        { es: "sazonar", sv: "krydda" },
        { es: "pelar", sv: "skala" },
        { es: "probar", sv: "prova" },
        { es: "rallar", sv: "riva" },
        { es: "sacar", sv: "ta ut" },
        { es: "hervir", sv: "koka" },
        { es: "servir", sv: "servera" },
        { es: "freír", sv: "steka" },
        { es: "echar", sv: "hälla" },
        { es: "mezclar", sv: "blanda" },
        { es: "apagar", sv: "stänga av" },
        { es: "comer", sv: "äta" }
      ],
      sentences: [
        { es: "Vas a cortar el pescado en trozos.", sv: "Du ska skära fisken i bitar." },
        { es: "Vas a picar la cebolla con el cuchillo.", sv: "Du ska hacka löken med kniven." },
        { es: "Vas a hervir las patatas durante 20 minutos.", sv: "Du ska koka potatisen i 20 minuter." },
        { es: "Vas a freír el pescado en una sartén.", sv: "Du ska steka fisken i en stekpanna." },
        { es: "Vas a sazonar con una cucharadita de sal.", sv: "Du ska krydda med en tesked salt." },
        { es: "Vas a añadir aceite de oliva, limón, sal y pimienta.", sv: "Du ska lägga till olivolja, citron, salt och peppar." },
        { es: "¡Buen provecho!", sv: "Smaklig måltid!" }
      ]
    },
    {
      id: "verb-vanliga",
      name: "Vanliga verb",
      icon: "📝",
      description: "Verb du behöver kunna",
      words: [
        { es: "usar", sv: "använda" },
        { es: "comer", sv: "äta" },
        { es: "vivir", sv: "bo" },
        { es: "comprar", sv: "köpa" },
        { es: "necesitar", sv: "behöva" },
        { es: "llevar", sv: "bära" },
        { es: "dejar", sv: "lämna" },
        { es: "beber", sv: "dricka" },
        { es: "hacer", sv: "göra" },
        { es: "tomar", sv: "ta" },
        { es: "pagar", sv: "betala" },
        { es: "estudiar", sv: "studera" },
        { es: "llegar", sv: "anlända" },
        { es: "visitar", sv: "besöka" },
        { es: "recibir", sv: "ta emot" },
        { es: "ver", sv: "se" },
        { es: "tocar", sv: "spela (instrument)" },
        { es: "escribir", sv: "skriva" },
        { es: "entrenar", sv: "träna" },
        { es: "trabajar", sv: "jobba" },
        { es: "terminar", sv: "sluta" },
        { es: "mandar", sv: "skicka" },
        { es: "hablar", sv: "prata" },
        { es: "abrir", sv: "öppna" }
      ]
    },
    {
      id: "verb-diftong",
      name: "Diftongerande verb",
      icon: "🔄",
      description: "Verb som byter vokal i presens",
      words: [
        { es: "querer", sv: "vilja" },
        { es: "entender", sv: "förstå" },
        { es: "pensar", sv: "tänka" },
        { es: "sentir", sv: "känna" },
        { es: "tener", sv: "ha" },
        { es: "poder", sv: "kunna" },
        { es: "encontrar", sv: "hitta" },
        { es: "dormir", sv: "sova" },
        { es: "volar", sv: "flyga" },
        { es: "probar", sv: "prova" }
      ],
      sentences: [
        { es: "Me siento un poco cansado.", sv: "Jag känner mig lite trött." },
        { es: "Quieren estar de vacaciones.", sv: "De vill vara på semester." },
        { es: "Entendemos que quieres abrir la ventana.", sv: "Vi förstår att du vill öppna fönstret." },
        { es: "Tienen una casa en un pueblo pequeño.", sv: "De har ett hus i en liten by." },
        { es: "Queremos encontrar el cuerpo.", sv: "Vi vill hitta kroppen." },
        { es: "¿Tienes el espejo?", sv: "Har du spegeln?" }
      ]
    },
    {
      id: "personlighet",
      name: "Personlighet och utseende",
      icon: "🙂",
      description: "Beskriv dig själv och andra",
      words: [
        { es: "bajo", sv: "kort" },
        { es: "alto", sv: "lång" },
        { es: "moreno", sv: "mörkhårig" },
        { es: "rubio", sv: "ljushårig" },
        { es: "delgado", sv: "smal" },
        { es: "marrón", sv: "brun" },
        { es: "una sonrisa", sv: "ett leende" },
        { es: "hablador", sv: "pratglad" },
        { es: "sociable", sv: "social" },
        { es: "curioso", sv: "nyfiken" },
        { es: "tímido", sv: "blyg" },
        { es: "extrovertido", sv: "utåtriktad" },
        { es: "cabezón", sv: "envis" }
      ],
      sentences: [
        { es: "Soy baja, rubia y musculosa.", sv: "Jag är kort, blond och muskulös." },
        { es: "Tengo los ojos marrones y una sonrisa grande.", sv: "Jag har bruna ögon och ett stort leende." },
        { es: "Me gustan los deportes.", sv: "Jag gillar sporter." },
        { es: "En mi tiempo libre también me gusta leer libros.", sv: "På min fritid tycker jag också om att läsa böcker." },
        { es: "También me gustan los idiomas y viajar.", sv: "Jag gillar också språk och att resa." },
        { es: "Soy habladora, sociable y curiosa.", sv: "Jag är pratglad, social och nyfiken." },
        { es: "No soy una persona tímida.", sv: "Jag är inte en blyg person." }
      ]
    },
    {
      id: "fritid",
      name: "Fritid och aktiviteter",
      icon: "⚽",
      description: "Vad du gör på fritiden",
      words: [
        { es: "entrenar", sv: "träna" },
        { es: "esquiar", sv: "åka skidor" },
        { es: "jugar al tenis", sv: "spela tennis" },
        { es: "jugar al baloncesto", sv: "spela basket" },
        { es: "el tiempo libre", sv: "fritiden" },
        { es: "leer libros", sv: "läsa böcker" },
        { es: "hacer skate", sv: "åka skateboard" },
        { es: "viajar", sv: "resa" },
        { es: "un idioma", sv: "ett språk" },
        { es: "tocar el piano", sv: "spela piano" },
        { es: "tocar la guitarra", sv: "spela gitarr" },
        { es: "escuchar la música", sv: "lyssna på musik" },
        { es: "jugar videojuegos", sv: "spela tv-spel" },
        { es: "una peli", sv: "en film" },
        { es: "ir de compras", sv: "shoppa" },
        { es: "la ropa", sv: "kläder" },
        { es: "salir", sv: "gå ut" },
        { es: "decir", sv: "säga" },
        { es: "me gusta", sv: "jag gillar" }
      ]
    },
    {
      id: "sjukhus",
      name: "På sjukhuset",
      icon: "🏥",
      description: "Fraser för telefon och sjukhus",
      sentences: [
        { es: "Dígame.", sv: "Hallå (på telefon)." },
        { es: "Soy yo.", sv: "Det är jag." },
        { es: "¿Qué tal, cariño?", sv: "Hur är det, älskling?" },
        { es: "Estoy en el hospital.", sv: "Jag är på sjukhuset." },
        { es: "¿Qué dice?", sv: "Vad säger du?" },
        { es: "Tengo la pierna rota.", sv: "Mitt ben är brutet." },
        { es: "¿Por qué?", sv: "Varför det?" },
        { es: "Un carro me golpeó.", sv: "En bil körde på mig." },
        { es: "¿Te duele mucho?", sv: "Har du mycket ont?" },
        { es: "Me muevo con las muletas.", sv: "Jag rör mig med kryckorna." },
        { es: "¿Por qué no usas casco?", sv: "Varför använder du inte hjälm?" },
        { es: "No tienes que gritar.", sv: "Du behöver inte skrika." },
        { es: "No fue mi culpa.", sv: "Det var inte mitt fel." },
        { es: "Voy al hospital.", sv: "Jag åker till sjukhuset." },
        { es: "No tienes que venir.", sv: "Du behöver inte komma." },
        { es: "Voy enseguida.", sv: "Jag åker genast." },
        { es: "Vale.", sv: "Ok." },
        { es: "Tienes que descansar.", sv: "Du måste vila." },
        { es: "Chao, mi hija.", sv: "Hejdå, min dotter." }
      ]
    },
    {
      id: "personlig-info",
      name: "Personliga frågor",
      icon: "💬",
      description: "Frågor om dig själv",
      sentences: [
        { es: "¿Cómo te llamas?", sv: "Vad heter du?" },
        { es: "¿Cuántos años tienes?", sv: "Hur gammal är du?" },
        { es: "¿Cuándo es tu cumpleaños?", sv: "När är din födelsedag?" },
        { es: "¿Dónde vives?", sv: "Var bor du?" },
        { es: "¿Tienes hermanos?", sv: "Har du syskon?" },
        { es: "¿Tienes mascotas?", sv: "Har du husdjur?" },
        { es: "¿Qué te gusta hacer en tu tiempo libre?", sv: "Vad gillar du att göra på fritiden?" }
      ]
    },
    {
      id: "futurum",
      name: "Vad ska du göra? (futurum)",
      icon: "📅",
      description: "Frågor om vad du ska göra",
      sentences: [
        { es: "¿Vas a estudiar esta semana?", sv: "Ska du plugga den här veckan?" },
        { es: "¿Vas a comer algo rico esta semana?", sv: "Ska du äta något gott den här veckan?" },
        { es: "¿Vas a visitar a un abuelo esta semana?", sv: "Ska du besöka en farförälder den här veckan?" },
        { es: "¿Vas a tocar un instrumento esta semana?", sv: "Ska du spela ett instrument den här veckan?" },
        { es: "¿Vas a ir a una fiesta esta semana?", sv: "Ska du gå på fest den här veckan?" },
        { es: "¿Vas a trabajar esta semana?", sv: "Ska du jobba den här veckan?" },
        { es: "¿Vas a entrenar esta semana?", sv: "Ska du träna den här veckan?" },
        { es: "¿Vas a cantar esta semana?", sv: "Ska du sjunga den här veckan?" },
        { es: "¿Vas a hacer tareas esta semana?", sv: "Ska du göra läxor den här veckan?" },
        { es: "¿Vas a limpiar tu habitación esta semana?", sv: "Ska du städa ditt rum den här veckan?" },
        { es: "¿Vas a leer un libro esta semana?", sv: "Ska du läsa en bok den här veckan?" },
        { es: "¿Vas a ver una película esta semana?", sv: "Ska du se en film den här veckan?" },
        { es: "¿Vas a hablar español esta semana?", sv: "Ska du prata spanska den här veckan?" },
        { es: "¿Vas a viajar esta semana?", sv: "Ska du resa den här veckan?" },
        { es: "¿Vas a lavar la ropa esta semana?", sv: "Ska du tvätta kläder den här veckan?" },
        { es: "¿Vas a cocinar esta semana?", sv: "Ska du laga mat den här veckan?" },
        { es: "¿Vas a correr esta semana?", sv: "Ska du springa den här veckan?" },
        { es: "¿Vas a bailar esta semana?", sv: "Ska du dansa den här veckan?" },
        { es: "¿Vas a escuchar música esta semana?", sv: "Ska du lyssna på musik den här veckan?" }
      ]
    },
    {
      id: "perfekt",
      name: "Vad har du gjort? (perfekt)",
      icon: "✅",
      description: "Frågor om förra veckan",
      sentences: [
        { es: "¿Has leído un libro?", sv: "Har du läst en bok?" },
        { es: "¿Has hablado inglés?", sv: "Har du pratat engelska?" },
        { es: "¿Has hablado español?", sv: "Har du pratat spanska?" },
        { es: "¿Has comido algo rico?", sv: "Har du ätit något gott?" },
        { es: "¿Has visitado a alguien?", sv: "Har du besökt någon?" },
        { es: "¿Has visto una película?", sv: "Har du sett en film?" },
        { es: "¿Has comprado algo?", sv: "Har du köpt något?" },
        { es: "¿Has entrenado?", sv: "Har du tränat?" },
        { es: "¿Has estado enfermo?", sv: "Har du varit sjuk?" },
        { es: "¿Has bailado?", sv: "Har du dansat?" },
        { es: "¿Has jugado al fútbol?", sv: "Har du spelat fotboll?" },
        { es: "¿Has estudiado?", sv: "Har du pluggat?" },
        { es: "¿Has hecho algo divertido?", sv: "Har du gjort något kul?" },
        { es: "¿Has hecho algo aburrido?", sv: "Har du gjort något tråkigt?" },
        { es: "¿Has cantado?", sv: "Har du sjungit?" }
      ]
    }
  ]
};
