// AUTO-GENERATED from Victor's KB Spanish vocab. DO NOT EDIT BY HAND.
// Regenerated by ~/.hermes/profiles/2-victor/scripts/spanska-kb-gen.py
// Each area = one vocab_*.md file. Loaded after data.js, before app.js.
(function () {
  if (typeof DATA === 'undefined' || !Array.isArray(DATA.areas)) return;
  const KB_AREAS = [
  {
    "id": "kb-vocab-1ab",
    "name": "Spanska Ordförråd - Kapitel 1AB",
    "icon": "📗",
    "description": "Från KB (vocab_1AB) · 2026-08-25",
    "words": [
      {
        "es": "una ciudad",
        "sv": "stad"
      },
      {
        "es": "una entrevista",
        "sv": "intervju"
      },
      {
        "es": "un/una cantante",
        "sv": "sångare/sångerska"
      },
      {
        "es": "una banda",
        "sv": "ett band"
      },
      {
        "es": "encantado/encantada",
        "sv": "trevligt att träffas"
      },
      {
        "es": "igual",
        "sv": "detsamma"
      },
      {
        "es": "tercero",
        "sv": "tredje"
      },
      {
        "es": "ahora",
        "sv": "nu"
      },
      {
        "es": "hijo/hija",
        "sv": "son/dotter"
      },
      {
        "es": "aquí",
        "sv": "här"
      },
      {
        "es": "cerca",
        "sv": "nära"
      },
      {
        "es": "otros/otras",
        "sv": "andra"
      },
      {
        "es": "un país",
        "sv": "ett land"
      },
      {
        "es": "entre",
        "sv": "mellan"
      },
      {
        "es": "distintos/distintas",
        "sv": "olika"
      },
      {
        "es": "tranquilo/tranquila",
        "sv": "lugn"
      },
      {
        "es": "todo",
        "sv": "allt"
      },
      {
        "es": "ti/tú",
        "sv": "dig/du"
      },
      {
        "es": "homenaje",
        "sv": "hyllning"
      },
      {
        "es": "una canción",
        "sv": "en sång/låt"
      },
      {
        "es": "la batería",
        "sv": "trummor"
      },
      {
        "es": "por ejemplo",
        "sv": "till exempel"
      },
      {
        "es": "tratar de",
        "sv": "handla om"
      },
      {
        "es": "la muerte",
        "sv": "döden"
      },
      {
        "es": "la vida",
        "sv": "livet"
      },
      {
        "es": "un lugar",
        "sv": "ett ställe"
      },
      {
        "es": "con",
        "sv": "med"
      },
      {
        "es": "por qué",
        "sv": "varför"
      },
      {
        "es": "porque",
        "sv": "eftersom, för att"
      },
      {
        "es": "tenía",
        "sv": "jag hade"
      },
      {
        "es": "cuántos/as",
        "sv": "hur många"
      },
      {
        "es": "cuáles",
        "sv": "vilka"
      },
      {
        "es": "querido/a",
        "sv": "kära"
      },
      {
        "es": "tocar",
        "sv": "spela (instrument)"
      },
      {
        "es": "cantar",
        "sv": "sjunga"
      },
      {
        "es": "era",
        "sv": "hen var"
      },
      {
        "es": "algún/alguna",
        "sv": "någon, något"
      },
      {
        "es": "Inglaterra",
        "sv": "England"
      },
      {
        "es": "de qué",
        "sv": "om vad"
      },
      {
        "es": "gracias",
        "sv": "tack för"
      },
      {
        "es": "una mezcla",
        "sv": "en blandning"
      },
      {
        "es": "los indígenas",
        "sv": "ursprungsbefolkningen"
      },
      {
        "es": "venir",
        "sv": "att komma"
      },
      {
        "es": "en los años cincuenta",
        "sv": "på 50-talet"
      },
      {
        "es": "llegar",
        "sv": "komma, anlända"
      },
      {
        "es": "Los Estados Unidos",
        "sv": "USA"
      },
      {
        "es": "evolucionar",
        "sv": "utvecklas"
      },
      {
        "es": "hoy",
        "sv": "idag"
      },
      {
        "es": "hay",
        "sv": "det finns"
      },
      {
        "es": "varios/varias",
        "sv": "olika"
      },
      {
        "es": "el estilo",
        "sv": "stilen"
      },
      {
        "es": "el origen",
        "sv": "ursprunget"
      },
      {
        "es": "viejo/vieja",
        "sv": "gammal"
      },
      {
        "es": "los jóvenes",
        "sv": "ungdomarna"
      },
      {
        "es": "entre",
        "sv": "mellan"
      },
      {
        "es": "nuevo/nueva",
        "sv": "ny"
      },
      {
        "es": "las semejanzas",
        "sv": "likheterna"
      },
      {
        "es": "tiene un boom",
        "sv": "har en boom"
      },
      {
        "es": "se visten de",
        "sv": "klär sig som"
      },
      {
        "es": "como",
        "sv": "som"
      },
      {
        "es": "la ropa",
        "sv": "kläder"
      },
      {
        "es": "ancho/ancha",
        "sv": "vid, bred"
      },
      {
        "es": "una gorra",
        "sv": "en keps"
      },
      {
        "es": "mezclar",
        "sv": "blanda"
      },
      {
        "es": "los esclavos",
        "sv": "slavarna"
      }
    ]
  }
];
  const existing = new Set(DATA.areas.map(a => a.id));
  for (const a of KB_AREAS) {
    if (!existing.has(a.id)) DATA.areas.push(a);
  }
})();
